### ISSUE TITLE
Lucene lock

### ISSUE THREAD

**Issue by bdukes** [sachatrauwaen/OpenContent#105]
We're somewhat consistently getting this error when adding and updating content on our client's site (this is the response to the `Update` request, the end user just sees an alert saying "Uh-oh, something broke: Internal Server Error", and nothing is logged in DNN's event viewer).  

Is there a fix in the code we can implement?  Has this been investigated before?  Is there something in our environment we should look into?

```
{
    "Message":"An error has occurred.",
    "ExceptionMessage":"Unable to create Lucene writer (lock file is in use). Please recycle AppPool in IIS to release lock.",
    "ExceptionType":"System.Exception",
    "StackTrace":" at Satrabel.OpenContent.Components.Lucene.LuceneService.get_Writer()\r\n
        at Satrabel.OpenContent.Components.Lucene.LuceneService.Add(Document doc)\r\n 
        at Satrabel.OpenContent.Components.Datasource.OpenContentDataSource.Add(DataSourceContext context, JToken data)\r\n 
        at Satrabel.OpenContent.Components.OpenContentAPIController.Update(JObject json)",
    "InnerException":{
        "Message":"An error has occurred.",
        "ExceptionMessage":"The process cannot access the file 'D:\\home\\site\\wwwroot\\App_Data\\OpenContent\\lucene_index\\write.lock' because it is being used by another process.",
        "ExceptionType":"System.IO.IOException",
        "StackTrace":" at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n 
            at System.IO.File.InternalDelete(String path, Boolean checkHost)\r\n 
            at Satrabel.OpenContent.Components.Lucene.LuceneService.get_Writer()"
    }
}
```

**Comment by sachatrauwaen** [comment]
First, i already seen this kind of errors in the past, in opencontent and also in dnn. This is due to the way lucene works, it's a file based system with his limitations.

That say, normally this only occurs if 2 process try to access lucene.
This normally not hapen, if you are not in a webfarm configuration.
Lucene is not compatible with webfarm.

Or this can maybe also happen after iis process crach or if you bad configure iis and have 2 iis websites pointing to the same dnn folder.

That say, i am very happy if we can make opencontent code more robust and if we do better error logging. So all ideas and contributions are welcom
