### ISSUE TITLE
Bootstrap 4, FontAwesome 5?

### ISSUE THREAD

**Issue by pjones235** [sachatrauwaen/OpenContent#37]
I'm thinking it would be worth upgrading to Bootstrap 4 and FontAwesome 5. I'm willing to give a pull request if there's interest.

**Comment by sachatrauwaen** [comment]
For templates, it will be nice if you create Bootstrap 4 versions.
I will include them as additional available templates.

In editor that is based on alpacajs, it sound difficult, because alpacajs don't support actually bootstrap 4.

I had a look at fontawesome 5 it sound nice. 
But it's not 100% backward compatible .
If you want to integrate fontawesome 5, it need to be an new option in the icon field.

**Comment by pjones235** [comment]
FontAwesome has a shim file that can be used for backward compatibility. Maybe something to look at.
I'll make a pull request in the next couple of weeks.

**Comment by sachatrauwaen** [comment]
Thanks.
