### ISSUE TITLE
Additional Fields from Alpaca.

### ISSUE THREAD

**Issue by robert-m** [sachatrauwaen/OpenContent#38]
Hi Sacha! Are there any plans to upgrade to the latest Alpaca version?

I'm trying to use some of the other Alpaca fields such as the **'Color Pick'** in my `options.json` but its not compatible with the current OpenContent version.

**Comment by robert-m** [comment]
Thank you for the prompt reply @sachatrauwaen.

I did have a look at the one you suggested but unfortunately you can't pre-define a set of colors with this field type which is something I require.

**Comment by anpa8** [comment]
Hi,
is it possible to get a readonly-checkbox for fields in openForm? I'll try to put manuel options in json-Files but don't work. I would like to save username etc which send the form and won't give a field, that can changed by user.

**Comment by sachatrauwaen** [comment]
You can with readobly property in schemo or options file.
http://www.alpacajs.org/docs/fields/text.html
Or you can also try with display view
http://www.alpacajs.org/docs/api/views.html

**Comment by anpa8** [comment]
i know that options, but i don't know where i have to put that options in template.All what i've tried will not work.--- Ursprüngliche Nachricht ---Von: Sacha <notifications@github.com>Datum: 07.05.2019 12:35:54An: sachatrauwaen/OpenContent <OpenContent@noreply.github.com>Betreff: Re: [sachatrauwaen/OpenContent] Additional Fields from Alpaca. (#38)You can with readobly property in schemo or options file.
http://www.alpacajs.org/docs/fields/text.html
Or you can also try with display view
http://www.alpacajs.org/docs/api/views.html

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sachatrauwaen/OpenContent/issues/38#issuecomment-490027420",
"url": "https://github.com/sachatrauwaen/OpenContent/issues/38#issuecomment-490027420",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sachatrauwaen** [comment]
alpaca schema options need to be putted in schema.json in your template folder
alpaca  options need to be putted in options.json in your template folder

if the form builder is activated, you need to deactivate it by delete the file builder.json otherwise the scha.json and options.json will be override when you mak changes in the form builder.

When you have deactivated the form builder you can edit the schema.json and options.json frol Edit Template files

**Comment by anpa8** [comment]
this is my options.json:

{
  "fields": {
    "DisplayName": {
      "type": "text",
      "readonly": true
    },
    "Betreff": {
      "type": "text"
    },
    "Nachricht": {
      "type": "textarea"
    }
  }
}

if i added the "readonly": true, the field is not visible in form, but the field works (sends data).
But i would like to see the field in form :-(

**Comment by anpa8** [comment]
This is my schema.json:

{
  "type": "object",
  "properties": {
    "DisplayName": {
      "type": "string",
      "title": "Name",
      "required": true,
      "readonly": true
    },
    "Betreff": {
      "type": "string",
      "title": "Betreff",
      "required": true
    },
    "Nachricht": {
      "type": "string",
      "title": "Nachricht",
      "required": true
    }
  }
}

the readonly: true has the same as in options.json: it is not visible.

**Comment by sachatrauwaen** [comment]
I dont see sothing wrong in your schema.
I just test it in opencontent and work ok.

You can also test exemple 3 on this page
http://www.alpacajs.org/docs/fields/text.html
by adding "readonly": true in the schema and click run.
If works as espected.
