### ISSUE TITLE
Edit content missing glyphs, weird buttons

### ISSUE THREAD

**Issue by aldeng11** [sachatrauwaen/OpenContent#79]
This may have something to do with issue #74 

There are weird buttons at the top of Edit Content that don't seem to do anything.  Also, glyphs missing and content overflows on right.
![image](https://user-images.githubusercontent.com/27434298/59309464-776aa800-8c58-11e9-991b-10e6038f76e9.png)

**Comment by sachatrauwaen** [comment]
Maybe because you using bootstrap 4 in edit skin.
OpenContent Bootstrap layout in edit forms is made for bootstrap 3.
You can try dnn layout in global settings

**Comment by aldeng11** [comment]
DNN layout loses glyphicons and has so many layout issues that it makes all features unusable.

**Comment by sachatrauwaen** [comment]
Actually, opencontent edit form are made for bootstrap 3.
Because your popup skin inject bootstrap 4, there are some layout issues.

The only way i see to solve is to change the popupskin included in your skin.
Just remove base-1.min.css (this include bootstrap 4) in the popupskin.

Then change oc global settings to include bootstrap (v3).

This will normally solve the layout issues.

**Comment by b-creative** [comment]
or do not use popups :)

**Comment by aldeng11** [comment]
If I remove that file, it will break all pop-ups on my site.  Bootstrap 4 is mainstream.

**Comment by sachatrauwaen** [comment]
That sound strange, dnn do not require bootstrap.

When you say "all popups", witch popups are really not work anymore ?

Module settings, login ? or specific module popups ?

**Comment by Timo-Breumelhof** [comment]
I'm using OC 4.2 with a BS 4 skins and see no issues with the right settings (and DNN pop-ups off)

**Comment by Timo-Breumelhof** [comment]
Oke, just to be sure, I just tested with my BS4 skin. Both without popups and with pop-ups I cannot reproduce the issue.
I loaded BS4 (CSS) in my popUpSkin.ascx (while IMO that skin should be "Empty") 
Might be the skin used adds more?
I have the attached settings in OC Global settings.
![image](https://user-images.githubusercontent.com/8999382/59496252-56d96280-8e91-11e9-8f1c-d5236c7ceef3.png)

**Comment by perezandres** [comment]
I have that issue (my skin is based on BS 4) only with popups DISABLED; if I enable popups, everything is OK.

**Comment by sachatrauwaen** [comment]
> I have that issue (my skin is based on BS 4) only with popups DISABLED; if I enable popups, everything is OK.

What are your global settings (2 settings for bootstrap) ?
Do you have errors in the browser console ?

**Comment by perezandres** [comment]
> > I have that issue (my skin is based on BS 4) only with popups DISABLED; if I enable popups, everything is OK.
> 
> What are your global settings (2 settings for bootstrap) ?
> Do you have errors in the browser console ?

Console OK.
I've tried all possible variations of "Load Bootstrap on Edit Form" and "Load Glyphicons on Edit Form (for bootstrap 4)" but with none of them (4) I get a nice UI. I lose the icons and/or get a small typography.

**Comment by Timo-Breumelhof** [comment]
@perezandres 
I have "Load Bootstrap" off and "Load Glyphicons" on. (see screen print above) with pop-ups switched off.
But I did have the issue of the font getting small.
This was caused by the fact that the skin set the size of the body font to a smaller pixel value (this Skin was BS 3 before).
```
body {
    font-size: 12px;
}
```
You should not do that with BS 4, it will lead to this and other styling issues I noticed.
Set the font size on the html element and the rest will inherit using rem.

For the pop-up skin make sure it does not load bootstrap (which as @sachatrauwaen stated should not be needed by DNN)

**Comment by perezandres** [comment]
@Timo-Breumelhof 

OK, with popups disabled and OC global settings as you I get icons back, but with a weird green colour. This is my fault, as I'm also using Material Design for Bootstrap. I guess I'll have to lighten a bit this web... ;-)

Thank you!
